dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - libvorbis-dev
      - libopenal-dev
#      - freetype
#      - jpeg
#      - x11
#      - xrandr
#      - xcb
#      - x11-xcb
#      - xcb-randr
#      - xcb-image
#      - opengl
#      - flac
#      - ogg
#      - pthread
script:
  - cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ./
