dist: xenial
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    packages:
      - gcc-6.2
      - cmake-3.5
      - libsfml-dev
script:
  - cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ./
after_success:
  coveralls
