dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - libvorbis-dev
      - libopenal-dev
      - libxrandr-dev
      - libudev-dev
      - libflac-dev
script:
# Link gcc-6 and g++-6 to their standard commands
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-6 /usr/bin/g++
  - gcc -v
  - g++ -v
  - cmake --version
# Create directory 'build' to not clutter up the root dir
# CLion does this with the an option:
# File -> Settings -> Build, Execution, Deployment -> CMake -> Generation path
# Just set it to ./build
# Run cmake in RacingToHell/build, but using the CMakeLists.txt from the parent directory (../)
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ../
# Run cmake build with generated build files
  - cd .. && cmake --build ./build --target RacingToHell -- -j 8
