dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    packages:
      - gcc-5
#      - freetype
#      - jpeg
#      - x11
#      - xrandr
#      - xcb
#      - x11-xcb
#      - xcb-randr
#      - xcb-image
#      - opengl
#      - flac
#      - ogg
#      - libvorbis
#      - libopenal
#      - pthread
script:
  - cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ./
