#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 0.9.{build}

branches:
  except:
    - gh-pages

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

clone_folder: c:\projects\RacingToHell

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

# to run your custom scripts instead of automatic MSBuild
build_script:
  - mkdir build
  - cd build
  - set CC=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin\gcc
  - set CXX=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin\g++
  - cmake -G "MinGW Makefiles" ../
  - mingw32-make

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: C:\projects\RacingToHell\bin

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  - provider: GitHub
    artifact: RacingToHellWindows.zip
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
