#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 0.9.{build}

branches:
  except:
    - gh-pages

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017
clone_folder: c:\projects\RacingToHell

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

# to run your custom scripts instead of automatic MSBuild
build_script:
  - windows/build

after_build:
  - 7z a RacingToHellWindows.zip ./bin/*

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: RacingToHellWindows.zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  - provider: GitHub
    artifact: RacingToHellWindows.zip
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
