#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 0.9.{build}

branches:
  except:
    - gh-pages

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

clone_folder: c:\projects\RacingToHell

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

# to run your custom scripts instead of automatic MSBuild
build_script:
  - git clone https://github.com/SFML/SFML
  - mkdir build
  - cd build
  - set CC=C:/mingw-w64/i686-5.3.0-posix-dwarf-rt_v4-rev0/mingw32/bin/gcc
  - set CXX=C:/mingw-w64/i686-5.3.0-posix-dwarf-rt_v4-rev0/mingw32/bin/g++
  - set CMAKE_C_COMPILER=C:/mingw-w64/i686-5.3.0-posix-dwarf-rt_v4-rev0/mingw32/bin/gcc
  - set CMAKE_CXX_COMPILER=C:/mingw-w64/i686-5.3.0-posix-dwarf-rt_v4-rev0/mingw32/bin/g++
  - set OLD_PATH=%PATH%
  - set PATH=C:/mingw-w64/i686-5.3.0-posix-dwarf-rt_v4-rev0/mingw32/bin;"C:/Program Files (x86)/CMake/bin";"C:/Program Files/Git/bin"
  - cmake -G "MinGW Makefiles" ../
  - mingw32-make
  - set PATH=%OLD_PATH%
  - cd ..

after_build:
  - 7z a RacingToHellWindows.zip build/bin

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: RacingToHellWindows.zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  - provider: GitHub
    artifact: RacingToHellWindows.zip
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
