name: Build Racing To Hell

on: push

permissions:
  contents: write

jobs:
  build-android:
    name: "Android"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Android Tests
        run: cd android && ./gradlew test

      - name: Run Android Build
        run: cd android && ./gradlew build

  build-web:
    name: "Web"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - run: mkdir build

      - name: Run CMake
        working-directory: build
        run: |
          source ../emsdk/emsdk_env.sh
          emcmake cmake ..

      - name: Build
        working-directory: build
        run: |
          cmake --build .
          mv html/RacingToHell.html html/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/html

  build-linux:
    name: "Linux"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build . -t build-image
      - name: Run Build
        run: docker run -v $(pwd):/app build-image

  build-windows:
    name: "Windows"
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"

      - run: mkdir build

      - name: Run CMake
        working-directory: build
        run: cmake ..

      - name: Build
        working-directory: build
        run: cmake --build .
