name: Build Racing To Hell

on: push

jobs:
  build-android:
    name: "Android"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Android Tests
        run: cd android && ./gradlew test

      - name: Run Android Build
        run: cd android && ./gradlew build

  build-linux:
    name: "Linux"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build . -t build-image
      - name: Run Build
        run: docker run -v $(pwd):/app build-image

  build-windows:
    name: "Windows"
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"

      - run: mkdir build

      - name: Run CMake
        working-directory: build
        run: cmake ..

      - name: Build
        working-directory: ./build
        run: cmake --build .
